<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.38">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Text Analysis Using R - 9&nbsp; Creating and Managing Corpora</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./10-quanteda-tokens.html" rel="next">
<link href="./08-quanteda-overview.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }"><div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Creating and Managing Corpora</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Text Analysis Using R</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/quanteda/Text-Analysis-Using-R" title="Source Code" class="sidebar-tool px-1"><i class="bi bi-github"></i></a>
    <a href="" title="Share" id="sidebar-tool-dropdown-0" class="sidebar-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-share"></i></a>
    <ul class="dropdown-menu" aria-labelledby="sidebar-tool-dropdown-0">
<li>
          <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=%7Curl%7C">
            <i class="bi bi-bi-twitter pe-1"></i>
          Twitter
          </a>
        </li>
        <li>
          <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=%7Curl%7C">
            <i class="bi bi-bi-facebook pe-1"></i>
          Facebook
          </a>
        </li>
        <li>
          <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=%7Curl%7C">
            <i class="bi bi-bi-linkedin pe-1"></i>
          LinkedIn
          </a>
        </li>
    </ul>
</div>
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Welcome</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface.html" class="sidebar-item-text sidebar-link">Preface</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./authors.html" class="sidebar-item-text sidebar-link">About the Authors</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-intro.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction and Motivation</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">R</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-r-basics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">R Basics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-r-workflow.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">R Workflow</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-r-strings.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Working with Text in R</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">Acquiring Texts</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-acquiring-files.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Working with Files</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-acquiring-packages.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Using Text Import Tools</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-acquiring-internet.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Obtaining Texts from the Internet</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">Managing Textual Data Using quanteda</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-quanteda-overview.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Introducing the <strong>quanteda</strong> Package</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-quanteda-corpus.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Creating and Managing Corpora</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-quanteda-tokens.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Creating and Managing tokens</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-quanteda-tokensadvanced.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Advanced Token Manipulation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-quanteda-dictionaries.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Creating and Managing Dictionaries</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-quanteda-dfms.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Building Document-Feature Matrices</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">Exploring and Describing Texts</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-exploring-description.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Describing Texts</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15-exploring-kwic.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Keywords-in-Context</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./16-exploring-dictionaries.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Applying Dictionaries</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./17-exploring-frequencies.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Most Frequent Words</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">Statistics for Comparing Texts</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./18-comparing-sophistication.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Profiling Lexical Patterns and Usage</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./19-comparing-documents.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Document Similarity and Distance</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./20-comparing-features.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Feature Similarity and Distance</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">Machine Learning for Texts</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./21-ml-supervised-scaling.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Supervised Document Scaling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./22-ml-unsupervised-scaling.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Unsupervised Document Scaling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./23-ml-classifiers.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Methods for Text Classification</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./24-ml-embedding.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Word Embedding Models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./25-ml-topicmodels.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Topic modelling</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">Further Methods for Texts</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./26-further-advanced-nlp.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Advanced NLP using R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./27-further-tidy.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Integrating “tidy” approaches</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./28-further-hardlanguages.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Text analysis in “Hard” Languages</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">References</a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true">Appendices</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./29-appendix-installation.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Installing the Required Tools</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./30-appendix-encoding.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Everything You Never Wanted to Know about Encoding</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./31-appendix-regex.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">A Survival Guide to Regular Expressions</span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><!-- margin-sidebar --><div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li><a href="#objectives" id="toc-objectives" class="nav-link active" data-scroll-target="#objectives"> <span class="header-section-number">9.1</span> Objectives</a></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods"> <span class="header-section-number">9.2</span> Methods</a></li>
  <li>
<a href="#examples" id="toc-examples" class="nav-link" data-scroll-target="#examples"> <span class="header-section-number">9.3</span> Examples</a>
  <ul class="collapse">
<li><a href="#changing-the-unit-of-analysis" id="toc-changing-the-unit-of-analysis" class="nav-link" data-scroll-target="#changing-the-unit-of-analysis"> <span class="header-section-number">9.3.1</span> Changing the Unit of Analysis</a></li>
  <li><a href="#creating-new-document-level-variables" id="toc-creating-new-document-level-variables" class="nav-link" data-scroll-target="#creating-new-document-level-variables"> <span class="header-section-number">9.3.2</span> Creating New Document-Level Variables</a></li>
  <li><a href="#subset-a-text-corpus" id="toc-subset-a-text-corpus" class="nav-link" data-scroll-target="#subset-a-text-corpus"> <span class="header-section-number">9.3.3</span> Subset a Text Corpus</a></li>
  </ul>
</li>
  <li>
<a href="#issues" id="toc-issues" class="nav-link" data-scroll-target="#issues"> <span class="header-section-number">9.4</span> Issues</a>
  <ul class="collapse">
<li><a href="#identifying-patterns-for-corpus-segmentation" id="toc-identifying-patterns-for-corpus-segmentation" class="nav-link" data-scroll-target="#identifying-patterns-for-corpus-segmentation"> <span class="header-section-number">9.4.1</span> Identifying Patterns for Corpus Segmentation</a></li>
  <li><a href="#reshaping-corpora-after-statistical-analyis-of-texts" id="toc-reshaping-corpora-after-statistical-analyis-of-texts" class="nav-link" data-scroll-target="#reshaping-corpora-after-statistical-analyis-of-texts"> <span class="header-section-number">9.4.2</span> Reshaping Corpora after Statistical Analyis of Texts</a></li>
  </ul>
</li>
  <li><a href="#further-reading" id="toc-further-reading" class="nav-link" data-scroll-target="#further-reading"> <span class="header-section-number">9.5</span> Further Reading</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"> <span class="header-section-number">9.6</span> Exercises</a></li>
  </ul><div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/quanteda/Text-Analysis-Using-R/edit/master/09-quanteda-corpus.qmd" class="toc-action">Edit this page</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title"><span id="quanteda-corpus" class="quarto-section-identifier d-none d-lg-block"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Creating and Managing Corpora</span></span></h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header><section id="objectives" class="level2" data-number="9.1"><h2 data-number="9.1" class="anchored" data-anchor-id="objectives">
<span class="header-section-number">9.1</span> Objectives</h2>
<p>In this section, we cover the corpus object. We explain why you need a text corpus for text analysis and how the selection of texts can affect your results and inferences. We also outline approaches for changing the unit of analysis (reshaping and segmenting corpora), how to filter a text corpus based on variables associated with texts, how to retrieve the raw texts from a text corpus, and how to manage metadata about a text corpus.</p>
</section><section id="methods" class="level2" data-number="9.2"><h2 data-number="9.2" class="anchored" data-anchor-id="methods">
<span class="header-section-number">9.2</span> Methods</h2>
<p>All text analysis projects involve choices about the texts to be analyzed. Creating a text corpus starts with defining a sample of the available texts, out of all possible texts you could have selected. Afterwards, the texts identified for analysis need to be collected, gathered in a text corpus, and (usually) accompanied by attributes that distinguish texts. Examples include the newspaper, the date of publication, and the article’s author <span class="citation" data-cites="benoit2020text">(<a href="references.html#ref-benoit2020text" role="doc-biblioref">Benoit 2020</a>)</span>. A text corpus could be all articles published on immigration in Irish newspapers, with each article constituting one document in the text corpus. These so-called document-level variables contain additional information on each document and allow researchers to distinguish between texts in their analysis.</p>
<p>In some text analysis applications, the sample could constitute the entirety of texts. Analyzing all texts released by the actor(s) of interest does not necessarily mean that an analysis is without problems. Selection issues can drive the information that is recorded. Texts or information that are not transcribed or published cannot be included in the analysis. When analyzing budget speeches, speaker selection is an important caveat. Parties strategically select Members of Parliament who can express their opinion on government policy and budget decisions <span class="citation" data-cites="herzog15cuts">(<a href="references.html#ref-herzog15cuts" role="doc-biblioref">Herzog and Benoit 2015</a>)</span>. The positions of politicians not selected for speaking at a budget debate, cannot be considered in the textual analysis. PROVIDE ANOTHER EXAMPLE? Researchers should therefore consider potential selection effects or systematic missingness of information when assembling a text corpus.</p>
<p>The selection of texts will determine the scope of the analysis, generalizability, and inferences you can draw from your analysis. The principles of your research design should justify the inclusion or exclusion of documents for analysis. For example, if you want to study rhetoric during televised debates, the corpus would be limited to transcripts of televised debates. When comparing issue salience in televised debates and campaign speeches, the corpus will include debate transcripts and speeches. Thus, the research question should drive document selection.</p>
<div class="callout-note callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>Including and comparing texts with very different characteristics may affect your analysis. For example, written speeches often differ from spoken speeches <span class="citation" data-cites="benoit19sophistication">(<a href="references.html#ref-benoit19sophistication" role="doc-biblioref">Benoit, Munger, and Spirling 2019</a>)</span>. Debates follow a different data-generating process than campaign speeches. Debates rely on questions and spontaneous responses, while politicians or their campaign teams draft campaign speeches well in advance. This does not mean that different types of text cannot or should not be compared since such a comparison can reveal structural differences based on the medium of communication. However, we would strongly advise you to identify structural differences between types of texts by comparing different groups of texts. We discuss how to differences in word usage across groups in <a href="17-exploring-frequencies.html"><span>Chapter&nbsp;17</span></a>. <a href="25-ml-topicmodels.html"><span>Chapter&nbsp;25</span></a> shows how to identify variation in topic prevalence for two or more groups of documents.</p>
</div>
</div>
</div>
<p>Besides selecting texts for analysis, researchers need to determine the unit of analysis of the text corpus. The unit of analysis should be driven by your research design. If a researcher is interested in textual features associated with likes and retweets on Twitter, the unit of analysis is an individual tweet. A project about the association between sentiment and real-time voter reactions may shift the unit of analysis could be a candidate’s speech utterance <span class="citation" data-cites="boussalis21reactions">(<a href="references.html#ref-boussalis21reactions" role="doc-biblioref">Boussalis et al. 2021</a>)</span>.</p>
</section><section id="examples" class="level2" data-number="9.3"><h2 data-number="9.3" class="anchored" data-anchor-id="examples">
<span class="header-section-number">9.3</span> Examples</h2>
<p>For demonstration, we will use the corpus of televised debate transcripts from the U.S. Presidential election campaign of 2020. Donald Trump and Joe Biden participated in two televised debates. The first debate took place in Cleveland, Ohio, on 29 September 2020. The two candidates met again in Nashville, Tennessee on 10 December.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> Following the <strong>quanteda</strong> naming conventinos, the object name starts with <code>data_</code> (since it contains data), followed by <code>corpus_</code> (indicating that the object is a text corpus) and <code>debates</code>, describing the text corpus.</p>
<p>First, we inspect the text corpus using the <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> and <code><a href="https://quanteda.io/reference/ndoc.html">ndoc()</a></code> functions.</p>
<div class="cell">

</div>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">data_corpus_debates</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Corpus consisting of 2 documents, showing 2 documents:

               Text Types Tokens Sentences
 Debate: 2020-09-29  2565  24548      1928
 Debate: 2020-10-22  2413  21652      1417
                                           location       date
 Case Western Reserve University in Cleveland, Ohio 2020-09-29
         Belmont University in Nashville, Tennessee 2020-10-22</code></pre>
</div>
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ndoc</span><span class="op">(</span><span class="va">data_corpus_debates</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2</code></pre>
</div>
</div>
<p>The corpus consists of 2 documents. When inspecting the output of <code>summary(data_corpus_debates)</code> reveals that each document currently is the full transcript (Biden, Trump, and moderator) of a debate. The first document, containing the transcripts of the debate in Cleveland contains 24,548 tokens, 2565 types (i.e., unique tokens) and 1928 sentences. The second debate in Nashville is slightly shorter (21,652 tokens and 2,413 types).</p>
<section id="changing-the-unit-of-analysis" class="level3" data-number="9.3.1"><h3 data-number="9.3.1" class="anchored" data-anchor-id="changing-the-unit-of-analysis">
<span class="header-section-number">9.3.1</span> Changing the Unit of Analysis</h3>
<p>When analyzing debates, researchers often move to the level of utterances. We can achieve this using <code><a href="https://quanteda.io/reference/corpus_segment.html">corpus_segment()</a></code>. In the transcript, an utterance starts with the speaker’s name in ALL CAPS, followed by a colon. The regular expression <code>"\\s*[[:upper:]]+:\\s+"</code> identifies speaker names in ALL CAPS (<code>\\s*[[:upper:]]+</code>), followed by a colon <code>+:</code> and a white space <code>\\s+</code>. For a primer on regular expression see <a href="31-appendix-regex.html"><span>Chapter&nbsp;C</span></a>.</p>
<div class="cell">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># segment text corpus to level of utterances</span></span>
<span><span class="va">data_corpus_debatesseg</span> <span class="op">&lt;-</span> <span class="fu">corpus_segment</span><span class="op">(</span><span class="va">data_corpus_debates</span>, </span>
<span>                                         pattern <span class="op">=</span>  <span class="st">"\\s*[[:upper:]]+:\\s+"</span>, </span>
<span>                                         valuetype <span class="op">=</span> <span class="st">"regex"</span>, </span>
<span>                                         case_insensitive <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># overview of text corpus; n = 4 prints only the first four documents</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">data_corpus_debatesseg</span>, n <span class="op">=</span> <span class="fl">4</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Corpus consisting of 1207 documents, showing 4 documents:

                 Text Types Tokens Sentences
 Debate: 2020-09-29.1   139    251        13
 Debate: 2020-09-29.2     6      6         1
 Debate: 2020-09-29.3     5      5         1
 Debate: 2020-09-29.4     3      3         1
                                           location       date       pattern
 Case Western Reserve University in Cleveland, Ohio 2020-09-29 \n\nWALLACE: 
 Case Western Reserve University in Cleveland, Ohio 2020-09-29   \n\nBIDEN: 
 Case Western Reserve University in Cleveland, Ohio 2020-09-29   \n\nTRUMP: 
 Case Western Reserve University in Cleveland, Ohio 2020-09-29   \n\nBIDEN: </code></pre>
</div>
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu">ndoc</span><span class="op">(</span><span class="va">data_corpus_debatesseg</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1207</code></pre>
</div>
</div>
</section><section id="creating-new-document-level-variables" class="level3" data-number="9.3.2"><h3 data-number="9.3.2" class="anchored" data-anchor-id="creating-new-document-level-variables">
<span class="header-section-number">9.3.2</span> Creating New Document-Level Variables</h3>
<p>The new corpus consists of 1207 utterances by the moderators and candidates. The document-level variable <code>pattern</code> assigned the speaker name to each document. We can create a new <code>speaker</code> document-level variable by combining functions from the <strong>stringr</strong> and <strong>quanteda.tidy</strong> packages: <code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code> creates a new <code>speaker</code> variable, and the stringr functions remove empty whitespaces (<code><a href="https://stringr.tidyverse.org/reference/str_trim.html">str_trim()</a></code>), the colon (<code><a href="https://stringr.tidyverse.org/reference/str_remove.html">str_remove_all()</a></code>) and change the names from UPPER CASE to Title Case (<code><a href="https://stringr.tidyverse.org/reference/case.html">str_to_title()</a></code>).</p>
<div class="cell">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st"><a href="http://stringr.tidyverse.org">"stringr"</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st">"quanteda.tidy"</span><span class="op">)</span></span>
<span></span>
<span><span class="va">data_corpus_debatesseg</span> <span class="op">&lt;-</span> <span class="va">data_corpus_debatesseg</span> <span class="op">|&gt;</span> </span>
<span>    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>speaker <span class="op">=</span> <span class="fu">stringr</span><span class="fu">::</span><span class="fu"><a href="https://stringr.tidyverse.org/reference/str_trim.html">str_trim</a></span><span class="op">(</span><span class="va">pattern</span><span class="op">)</span>,</span>
<span>           speaker <span class="op">=</span> <span class="fu">stringr</span><span class="fu">::</span><span class="fu"><a href="https://stringr.tidyverse.org/reference/str_remove.html">str_remove_all</a></span><span class="op">(</span><span class="va">speaker</span>, <span class="st">":"</span><span class="op">)</span>,</span>
<span>           speaker <span class="op">=</span> <span class="fu">stringr</span><span class="fu">::</span><span class="fu"><a href="https://stringr.tidyverse.org/reference/case.html">str_to_title</a></span><span class="op">(</span><span class="va">speaker</span><span class="op">)</span><span class="op">)</span> </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Next, we can use simple base R functions to inspect the count of utterances by speaker and debate.</p>
<div class="cell">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># cross-table of speaker statements by debate</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">data_corpus_debatesseg</span><span class="op">$</span><span class="va">location</span>,</span>
<span>      <span class="va">data_corpus_debatesseg</span><span class="op">$</span><span class="va">speaker</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                                    
                                                     Biden Trump Wallace Welker
  Belmont University in Nashville, Tennessee            84   122       0    146
  Case Western Reserve University in Cleveland, Ohio   269   340     246      0</code></pre>
</div>
</div>
<p>We could further reshape the corpus to the level of sentences with <code><a href="https://quanteda.io/reference/corpus_reshape.html">corpus_reshape()</a></code> if we are interested, for instance, in sentence-level sentiment or issue salience.</p>
<div class="cell">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">data_corpus_debatessent</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://quanteda.io/reference/corpus_reshape.html">corpus_reshape</a></span><span class="op">(</span><span class="va">data_corpus_debatesseg</span>,</span>
<span>                                          to <span class="op">=</span> <span class="st">"sentences"</span><span class="op">)</span></span>
<span></span>
<span><span class="fu"><a href="https://quanteda.io/reference/ndoc.html">ndoc</a></span><span class="op">(</span><span class="va">data_corpus_debatessent</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3564</code></pre>
</div>
</div>
<p>The new text corpus moved from 1207 utterances to 3564 sentences. Using functions such as <strong>quanteda.textstat</strong>’s <code><a href="https://quanteda.io/reference/textstat_summary.html">textstat_summary()</a></code> we can retrieve summary statistics about each sentence.</p>
<div class="cell">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="st"><a href="https://quanteda.io">"quanteda.textstats"</a></span><span class="op">)</span></span>
<span><span class="va">dat_summary_sents</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://quanteda.io/reference/textstat_summary.html">textstat_summary</a></span><span class="op">(</span><span class="va">data_corpus_debatessent</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># aggregated summary statistics</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">dat_summary_sents</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   document             chars            sents       tokens     
 Length:3564        Min.   :  3.00   Min.   :1   Min.   : 1.00  
 Class :character   1st Qu.: 24.00   1st Qu.:1   1st Qu.: 6.00  
 Mode  :character   Median : 41.00   Median :1   Median : 9.00  
                    Mean   : 55.46   Mean   :1   Mean   :12.27  
                    3rd Qu.: 73.00   3rd Qu.:1   3rd Qu.:16.00  
                    Max.   :414.00   Max.   :1   Max.   :79.00  
     types           puncts          numbers          symbols       
 Min.   : 1.00   Min.   : 0.000   Min.   :0.0000   Min.   :0.00000  
 1st Qu.: 6.00   1st Qu.: 1.000   1st Qu.:0.0000   1st Qu.:0.00000  
 Median : 9.00   Median : 1.000   Median :0.0000   Median :0.00000  
 Mean   :10.83   Mean   : 1.965   Mean   :0.0794   Mean   :0.01543  
 3rd Qu.:14.00   3rd Qu.: 3.000   3rd Qu.:0.0000   3rd Qu.:0.00000  
 Max.   :56.00   Max.   :15.000   Max.   :4.0000   Max.   :3.00000  
      urls                tags       emojis 
 Min.   :0.0000000   Min.   :0   Min.   :0  
 1st Qu.:0.0000000   1st Qu.:0   1st Qu.:0  
 Median :0.0000000   Median :0   Median :0  
 Mean   :0.0005612   Mean   :0   Mean   :0  
 3rd Qu.:0.0000000   3rd Qu.:0   3rd Qu.:0  
 Max.   :1.0000000   Max.   :0   Max.   :0  </code></pre>
</div>
</div>
</section><section id="subset-a-text-corpus" class="level3" data-number="9.3.3"><h3 data-number="9.3.3" class="anchored" data-anchor-id="subset-a-text-corpus">
<span class="header-section-number">9.3.3</span> Subset a Text Corpus</h3>
<p>The last example in this chapter covers subsetting a text corpus based on document-level variables. Researchers who want to compare Trump and Biden may not be interested in the moderator’s statements. We can exclude the moderators with <code><a href="https://quanteda.io/reference/corpus_subset.html">corpus_subset()</a></code>.</p>
<div class="cell">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">data_corpus_debatescand</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://quanteda.io/reference/corpus_subset.html">corpus_subset</a></span><span class="op">(</span><span class="va">data_corpus_debatesseg</span>,</span>
<span>                                          <span class="va">speaker</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Trump"</span>, <span class="st">"Biden"</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># check that subsetting worked as expected</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">data_corpus_debatescand</span><span class="op">$</span><span class="va">speaker</span>,</span>
<span>      <span class="va">data_corpus_debatescand</span><span class="op">$</span><span class="va">location</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       
        Belmont University in Nashville, Tennessee
  Biden                                         84
  Trump                                        122
       
        Case Western Reserve University in Cleveland, Ohio
  Biden                                                269
  Trump                                                340</code></pre>
</div>
</div>
</section></section><section id="issues" class="level2" data-number="9.4"><h2 data-number="9.4" class="anchored" data-anchor-id="issues">
<span class="header-section-number">9.4</span> Issues</h2>
<section id="identifying-patterns-for-corpus-segmentation" class="level3" data-number="9.4.1"><h3 data-number="9.4.1" class="anchored" data-anchor-id="identifying-patterns-for-corpus-segmentation">
<span class="header-section-number">9.4.1</span> Identifying Patterns for Corpus Segmentation</h3>
<p>Segmenting corpora into smaller units requires a common pattern across the documents. In the example above, we identified utterances based on the combination of a speaker’s surname in capital letters followed by a colon. Other corpora may include markers such as line breaks or headings that can be used to segment a corpus. When segmenting text corpora, we strongly recommend inspecting the resulting text corpus and spot-check that the segmentation worked as expected.</p>
</section><section id="reshaping-corpora-after-statistical-analyis-of-texts" class="level3" data-number="9.4.2"><h3 data-number="9.4.2" class="anchored" data-anchor-id="reshaping-corpora-after-statistical-analyis-of-texts">
<span class="header-section-number">9.4.2</span> Reshaping Corpora after Statistical Analyis of Texts</h3>
<p>In many applications, the unit of analysis of the text corpus differs from the dataset used for statistical analyses. For example, <span class="citation" data-cites="castanhosilva22eu">Castanho Silva and Proksch (<a href="references.html#ref-castanhosilva22eu" role="doc-biblioref">2021</a>)</span> study sentiment on European politics in tweets and parliamentary speeches. The authors construct a corpus of speeches and tweets that mention keywords relating to Europe or the EU and apply a sentiment dictionary to each document. The authors aggregate sentiment to the level of all relevant texts by a single politician, moving from over 100,000 Europe-related tweets and 20,000 Europe-related speeches to around 2500 observations. Each observation stores the sentiment by one Member of Parliament during their period of investigation. These sentiment scores are then used in regression models.</p>
<p><span class="citation" data-cites="mueller22temporal">Müller (<a href="references.html#ref-mueller22temporal" role="doc-biblioref">2022</a>)</span> studied the temporal focus of parties’ campaign communication. First, he reshaped party manifestos to the level of sentences before identifying the temporal focus of each sentence using supervised classification (<a href="23-ml-classifiers.html"><span>Chapter&nbsp;23</span></a>). The regression models use an aggregated dataset with only three observations per manifesto (sentiment in sections about the past, present, and future).</p>
<div class="callout-tip callout callout-style-simple">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>Applying the <code>group_by()</code> in combination with the <code>summarise()</code> functions of the <strong>dplyr</strong> packages allows you to reshape the output of a textual analysis, stored as a data frame, to a higher-level unit of analysis.</p>
</div>
</div>
</div>
</section></section><section id="further-reading" class="level2" data-number="9.5"><h2 data-number="9.5" class="anchored" data-anchor-id="further-reading">
<span class="header-section-number">9.5</span> Further Reading</h2>
<ul>
<li>Selecting document and considerations of “found data”: <span class="citation" data-cites="grimmer22textasdata">Grimmer, Roberts, and Stewart (<a href="references.html#ref-grimmer22textasdata" role="doc-biblioref">2022</a>, ch.&nbsp;4)</span>
</li>
<li>Adjusting strings: <span class="citation" data-cites="wickham17r4ds">Wickham and Grolemund (<a href="references.html#ref-wickham17r4ds" role="doc-biblioref">2017</a>, ch.&nbsp;14)</span>
</li>
</ul></section><section id="exercises" class="level2" data-number="9.6"><h2 data-number="9.6" class="anchored" data-anchor-id="exercises">
<span class="header-section-number">9.6</span> Exercises</h2>
<p>In the exercises below, we use a corpus of speeches from the 2017 UN General Debates (<code>data_corpus_ungd2017</code>, included in the <strong>quanteda.corpora</strong> package).<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<ol type="1">
<li>Identify the number of documents in <code>data_corpus_ungd2017</code>.</li>
<li>Select only speeches delivered by representatives of African and Asian countries.</li>
<li>Reshape this subsetted corpus to the level of sentences.</li>
<li>Explore <code><a href="https://quanteda.io/reference/textstat_summary.html">textstat_summary()</a></code> of the <strong>quanteda.textstats</strong> package. Apply the function to <code>data_corpus_ungd2017</code> and assign it to an object called <code>tstat_sum_ungd</code>.</li>
<li>What are the average, median, minimum, and maximum document lengths?</li>
<li>Advanced: filter only speeches consisting of at least ?? tokens.</li>
<li>Advanced: use <code>tstat_sum_ungd</code> and create a histogram of document length using the <strong>ggplot2</strong> package.</li>
<li>Advanced: rerun the code for plotting the distribution, but add <code>facet_wrap()</code> and create small multiples for each continent.</li>
</ol>


<div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography" style="display: none">
<div id="ref-benoit2020text" class="csl-entry" role="doc-biblioentry">
Benoit, Kenneth. 2020. <span>“Text as Data: An Overview.”</span> In <em>Handbook of Research Methods in Political Science and International Relations</em>, edited by Luigi Curini and Robert Franzese, 461–97. Thousand Oaks: Sage.
</div>
<div id="ref-benoit19sophistication" class="csl-entry" role="doc-biblioentry">
Benoit, Kenneth, Kevin Munger, and Arthur Spirling. 2019. <span>“Measuring and Explaining Political Sophistication Through Textual Complexity.”</span> <em>American Journal of Political Science</em> 63 (2): 491–508. <a href="https://doi.org/10.1111/ajps.12423">https://doi.org/10.1111/ajps.12423</a>.
</div>
<div id="ref-boussalis21reactions" class="csl-entry" role="doc-biblioentry">
Boussalis, Constantine, Travis G. Coan, Mirya R. Holman, and Stefan Müller. 2021. <span>“Gender, Candidate Emotional Expression, and Voter Reactions During Televised Debates.”</span> <em>American Political Science Review</em> 115 (4): 1242–57. <a href="https://doi.org/10.1017/S0003055421000666">https://doi.org/10.1017/S0003055421000666</a>.
</div>
<div id="ref-castanhosilva22eu" class="csl-entry" role="doc-biblioentry">
Castanho Silva, Bruno, and Sven-Oliver Proksch. 2021. <span>“Politicians Unleashed? Political Communication on Twitter and in Parliament in Western Europe.”</span> <em>Political Science Research and Methods</em> published ahead of print (doi: 10.1017/psrm.2021.36). <a href="https://doi.org/10.1017/psrm.2021.36">https://doi.org/10.1017/psrm.2021.36</a>.
</div>
<div id="ref-grimmer22textasdata" class="csl-entry" role="doc-biblioentry">
Grimmer, Justin, Margaret E. Roberts, and Brandon M. Stewart. 2022. <em>Text as Data: The Promise and Pitfalls of Automatic Content Analysis Methods for Political Texts: A New Framework for Machine Learning and the Social Sciences</em>. Princeton: Princeton University Press.
</div>
<div id="ref-herzog15cuts" class="csl-entry" role="doc-biblioentry">
Herzog, Alexander, and Kenneth Benoit. 2015. <span>“The Most Unkindest Cuts: Speaker Selection and Expressed Goverment Dissent During Economic Crisis.”</span> <em>The Journal of Politics</em> 77 (4): 1157–75. <a href="https://doi.org/10.1086/682670">https://doi.org/10.1086/682670</a>.
</div>
<div id="ref-mueller22temporal" class="csl-entry" role="doc-biblioentry">
Müller, Stefan. 2022. <span>“The Temporal Focus of Campaign Communication.”</span> <em>The Journal of Politics</em> 84 (1): 585–90. <a href="https://doi.org/10.1086/715165">https://doi.org/10.1086/715165</a>.
</div>
<div id="ref-wickham17r4ds" class="csl-entry" role="doc-biblioentry">
Wickham, Hadley, and Garrett Grolemund. 2017. <em>R for Data Science: Import, Tidy, Transform, Visualize, and Model Data</em>. Sebastopol: O’Reilly. <a href="https://r4ds.had.co.nz">https://r4ds.had.co.nz</a>.
</div>
</div>
</section><section class="footnotes footnotes-end-of-document" role="doc-endnotes"><hr>
<ol>
<li id="fn1" role="doc-endnote"><p>The transcripts are available at https://www.presidency.ucsb.edu/documents/presidential-debate-case-western-reserve-university-cleveland-ohio and https://www.presidency.ucsb.edu/documents/presidential-debate-belmont-university-nashville-tennessee-0.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2" role="doc-endnote"><p>We will update the corpus before publishing the book and use the most recent UNGD speeches.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./08-quanteda-overview.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Introducing the <strong>quanteda</strong> Package</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./10-quanteda-tokens.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Creating and Managing tokens</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>