# Applying Dictionaries {#sec-exploring-dictionaries}

## Objectives

- The basic idea of counting token and feature matches as equivalence classes
- Matching phrases
- Weighting dictionary applications
- Multi-lingual applications
- Scaling dictionary results
- Confidence intervals and bootstrapping
- Dictionary validation using `kwic()`
- Dictionary construction using `textstat_keyness()`

Creating and revising dictionaries. 

- key-value lists 
- more details on pattern types 
- the `phrase()` argument 
- importing foreign dictionaries 
- editing dictionaries -
using dictionaries as `pattern` inputs to other functions
- exporting dictionaries 
- using dictionaries: `tokens_lookup()`

## Methods

Applicable methods for the objectives listed above.

## Examples

Sentiment analysis.

## Issues

Copyright.

Which format?

Weighted dictionaries.

Additional issues.

## Further Reading

On-line sources of dictionaries.

QI's **quanteda.dictionaries** package.

## Exercises

Add some here.
